# Generated by Django 4.0.5 on 2022-06-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samochód',
            name='cena',
        ),
        migrations.RemoveField(
            model_name='samochód',
            name='miejsca',
        ),
    ]
