# Generated by Django 4.0.5 on 2022-06-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0003_samochód_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochód',
            name='cena',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='samochód',
            name='miejsca',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
