# Generated by Django 4.0.5 on 2022-06-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0005_remove_samochód_autor_alter_samochód_klasa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='samochód',
            new_name='samochod',
        ),
    ]
