# Generated by Django 4.0.5 on 2022-06-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0006_rename_samochód_samochod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='samochod',
            new_name='samochody',
        ),
    ]
