# Generated by Django 4.0.5 on 2022-07-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0007_rename_samochod_samochody'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochody',
            name='image',
            field=models.ImageField(default='nocar.jpg', upload_to='car_pics'),
        ),
    ]
