# Generated by Django 4.0.5 on 2022-07-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0008_samochody_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samochody',
            name='cena',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
