# Generated by Django 4.0.5 on 2022-07-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0010_alter_samochody_skrzynia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samochody',
            name='klimatyzacja',
            field=models.CharField(blank=True, choices=[('0', 'Tak'), ('1', 'Nie')], max_length=20, null=True),
        ),
    ]
