# Generated by Django 4.0.5 on 2022-07-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0011_alter_samochody_klimatyzacja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samochody',
            name='paliwo',
            field=models.CharField(blank=True, choices=[('0', 'Benzyna'), ('1', 'Olej napedowy'), ('2', 'LPG')], max_length=50, null=True),
        ),
    ]
