# Generated by Django 4.0.5 on 2022-07-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0012_alter_samochody_paliwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochody',
            name='moc_silnika',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samochody',
            name='nadwozie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='samochody',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samochody',
            name='pojemnosc_silnika',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samochody',
            name='spalanie_miasto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samochody',
            name='spalanie_trasa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samochody',
            name='klimatyzacja',
            field=models.CharField(blank=True, choices=[('0', 'Manualna'), ('1', 'Automatyczna')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='samochody',
            name='paliwo',
            field=models.CharField(blank=True, choices=[('0', 'Benzyna'), ('1', 'Olej napędowy'), ('2', 'Benzyna + LPG'), ('3', 'Hybryda')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='samochody',
            name='skrzynia',
            field=models.CharField(blank=True, choices=[('0', 'Manualna'), ('1', 'Automatyczna')], max_length=11, null=True),
        ),
    ]
