# Generated by Django 4.0.5 on 2022-07-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0014_alter_samochody_moc_silnika_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samochody',
            old_name='opis',
            new_name='wyposazenie',
        ),
    ]
