# Generated by Django 4.0.5 on 2022-07-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0015_rename_opis_samochody_wyposazenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samochody',
            name='moc_silnika',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
