# Generated by Django 4.0.5 on 2022-07-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0018_alter_zamow_data_odbioru_alter_zamow_data_oddania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamow',
            name='data_odbioru',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zamow',
            name='data_oddania',
            field=models.DateField(blank=True, null=True),
        ),
    ]
