# Generated by Django 4.0.5 on 2022-07-05 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0020_alter_zamow_samochod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamow',
            name='samochod',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wynajem.samochody'),
        ),
    ]
