# Generated by Django 4.0.5 on 2022-07-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0022_alter_zamow_samochod_alter_zamow_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamow',
            name='samochod',
        ),
    ]
