# Generated by Django 4.0.5 on 2022-07-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0024_zamow_samochod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamow',
            name='miejsce_odbioru',
            field=models.CharField(blank=True, choices=[('0', 'Rzeszów, Dworzec Główny PKP'), ('1', 'Rzeszów, Lotnisko Jasionka'), ('2', 'Sopot, Dworzec Główny PKP'), ('3', 'Warszawa, Lotnisko Chopina'), ('4', 'Warszawa, Metro Wilanowska'), ('5', 'Warszawa, Dworzec Centralny'), ('6', 'Wrocław, Dworzec Główny PKP'), ('7', 'Sosnowiec, Dworzec Główny PKP'), ('8', 'Poznań, Lotnisko Ławica'), ('9', 'Olsztyn, Dworzec Główny PKP'), ('9', 'Łódź, Dworzec Łódź Kaliska')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zamow',
            name='miejsce_oddania',
            field=models.CharField(blank=True, choices=[('0', 'Rzeszów, Dworzec Główny PKP'), ('1', 'Rzeszów, Lotnisko Jasionka'), ('2', 'Sopot, Dworzec Główny PKP'), ('3', 'Warszawa, Lotnisko Chopina'), ('4', 'Warszawa, Metro Wilanowska'), ('5', 'Warszawa, Dworzec Centralny'), ('6', 'Wrocław, Dworzec Główny PKP'), ('7', 'Sosnowiec, Dworzec Główny PKP'), ('8', 'Poznań, Lotnisko Ławica'), ('9', 'Olsztyn, Dworzec Główny PKP'), ('9', 'Łódź, Dworzec Łódź Kaliska')], max_length=100, null=True),
        ),
    ]
