# Generated by Django 4.0.5 on 2022-07-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='telefon',
            field=models.CharField(default=345342567, max_length=17),
            preserve_default=False,
        ),
    ]
